version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order_management_app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mysql
      - redis
    networks:
      - order-net

  mysql:
    image: mysql:8
    container_name: order_management_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_management
      MYSQL_USER: orderuser
      MYSQL_PASSWORD: orderpass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - order-net

  redis:
    image: redis:latest
    container_name: order_management_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - order-net

networks:
  order-net:

volumes:
  mysql_data:
